# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.cache/wt [current_project]
set_property parent.project_path /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/new/UART_Tx.vhd
  /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/new/L1.vhd
  /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/imports/hdl/L1_block_wrapper.vhd
  /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/imports/hdl/L1_lru_wrapper.vhd
  /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/imports/hdl/L1_mru_wrapper.vhd
  /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/new/L2.vhd
  /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/imports/hdl/L2_block_wrapper.vhd
  /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/imports/hdl/L2_lru_wrapper.vhd
  /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/imports/hdl/L2_mru_wrapper.vhd
  /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/imports/hdl/traceram_wrapper.vhd
  /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/new/Controller.vhd
}
add_files /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/traceram/traceram.bd
set_property used_in_implementation false [get_files -all /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/traceram/ip/traceram_blk_mem_gen_0_0/traceram_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/traceram/traceram_ooc.xdc]

add_files /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/L2_mru/L2_mru.bd
set_property used_in_implementation false [get_files -all /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/L2_mru/ip/L2_mru_blk_mem_gen_0_0/L2_mru_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/L2_mru/L2_mru_ooc.xdc]

add_files /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/L2_lru/L2_lru.bd
set_property used_in_implementation false [get_files -all /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/L2_lru/ip/L2_lru_blk_mem_gen_0_0/L2_lru_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/L2_lru/L2_lru_ooc.xdc]

add_files /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/L2_block/L2_block.bd
set_property used_in_implementation false [get_files -all /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/L2_block/ip/L2_block_blk_mem_gen_0_0/L2_block_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/L2_block/L2_block_ooc.xdc]

add_files /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/L1_mru/L1_mru.bd
set_property used_in_implementation false [get_files -all /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/L1_mru/ip/L1_mru_blk_mem_gen_0_0/L1_mru_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/L1_mru/L1_mru_ooc.xdc]

add_files /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/L1_lru/L1_lru.bd
set_property used_in_implementation false [get_files -all /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/L1_lru/ip/L1_lru_blk_mem_gen_0_0/L1_lru_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/L1_lru/L1_lru_ooc.xdc]

add_files /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/L1_block/L1_block.bd
set_property used_in_implementation false [get_files -all /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/L1_block/ip/L1_block_blk_mem_gen_0_0/L1_block_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/sources_1/bd/L1_block/L1_block_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/constrs_1/new/basys.xdc
set_property used_in_implementation false [get_files /home/nk7/Lab6_BRAM_final/Lab6_BRAM2.srcs/constrs_1/new/basys.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top controller -part xc7a35ticpg236-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef controller.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file controller_utilization_synth.rpt -pb controller_utilization_synth.pb"
