# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/basys.xdc

# Block Designs: bd/traceram/traceram.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==traceram || ORIG_REF_NAME==traceram} -quiet] -quiet

# IP: bd/traceram/ip/traceram_blk_mem_gen_0_0/traceram_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==traceram_blk_mem_gen_0_0 || ORIG_REF_NAME==traceram_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/L2_mru/L2_mru.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L2_mru || ORIG_REF_NAME==L2_mru} -quiet] -quiet

# IP: bd/L2_mru/ip/L2_mru_blk_mem_gen_0_0/L2_mru_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L2_mru_blk_mem_gen_0_0 || ORIG_REF_NAME==L2_mru_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/L2_lru/L2_lru.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L2_lru || ORIG_REF_NAME==L2_lru} -quiet] -quiet

# IP: bd/L2_lru/ip/L2_lru_blk_mem_gen_0_0/L2_lru_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L2_lru_blk_mem_gen_0_0 || ORIG_REF_NAME==L2_lru_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/L2_block/L2_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L2_block || ORIG_REF_NAME==L2_block} -quiet] -quiet

# IP: bd/L2_block/ip/L2_block_blk_mem_gen_0_0/L2_block_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L2_block_blk_mem_gen_0_0 || ORIG_REF_NAME==L2_block_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/L1_mru/L1_mru.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L1_mru || ORIG_REF_NAME==L1_mru} -quiet] -quiet

# IP: bd/L1_mru/ip/L1_mru_blk_mem_gen_0_0/L1_mru_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L1_mru_blk_mem_gen_0_0 || ORIG_REF_NAME==L1_mru_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/L1_lru/L1_lru.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L1_lru || ORIG_REF_NAME==L1_lru} -quiet] -quiet

# IP: bd/L1_lru/ip/L1_lru_blk_mem_gen_0_0/L1_lru_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L1_lru_blk_mem_gen_0_0 || ORIG_REF_NAME==L1_lru_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/L1_block/L1_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L1_block || ORIG_REF_NAME==L1_block} -quiet] -quiet

# IP: bd/L1_block/ip/L1_block_blk_mem_gen_0_0/L1_block_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==L1_block_blk_mem_gen_0_0 || ORIG_REF_NAME==L1_block_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/traceram/traceram_ooc.xdc

# XDC: bd/L2_mru/L2_mru_ooc.xdc

# XDC: bd/L2_lru/L2_lru_ooc.xdc

# XDC: bd/L2_block/L2_block_ooc.xdc

# XDC: bd/L1_mru/L1_mru_ooc.xdc

# XDC: bd/L1_lru/L1_lru_ooc.xdc

# XDC: bd/L1_block/L1_block_ooc.xdc
