# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nk7/Lab6_BRAM2/Lab6_BRAM2.srcs/sources_1/bd/L1_mru/ip/L1_mru_blk_mem_gen_0_0/L1_mru_blk_mem_gen_0_0.xci
# IP: The module: 'L1_mru_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nk7/Lab6_BRAM2/Lab6_BRAM2.srcs/sources_1/bd/L1_mru/ip/L1_mru_blk_mem_gen_0_0/L1_mru_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'L1_mru_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/nk7/Lab6_BRAM2/Lab6_BRAM2.srcs/sources_1/bd/L1_mru/ip/L1_mru_blk_mem_gen_0_0/L1_mru_blk_mem_gen_0_0.xci
# IP: The module: 'L1_mru_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nk7/Lab6_BRAM2/Lab6_BRAM2.srcs/sources_1/bd/L1_mru/ip/L1_mru_blk_mem_gen_0_0/L1_mru_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'L1_mru_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
